name: helloworld-webapp
on: 
  push:
    branches: 
      - feature/taj
jobs:
    python-setup:
      runs-on: ubuntu-latest
      steps:
        - name: python setup
          uses: actions/setup-python@v3
          with:
            python-version: '3.x'

        # - name: repository-checkout
        #   uses: actions/checkout@v3

        - name: installing the dependencies
          run: |
            sudo apt install -y python3-pip
            python3 -m pip install PyPI
            python3 -V
            echo "python setup is completed"

    Build:
        runs-on: ubuntu-latest
        needs: python-setup

        steps:
        - name: repository-checkout
          uses: actions/checkout@v3

        - name: installing flask 
          run: |
            pip install flask
            python3 -c "import flask; print(flask.__version__)"

        - name: settingup dev-environment
          run: |
            # sudo apt install -y python3-venv
            # mkdir environments
            # cd environments
            # python3 -m venv development
            # source development/bin/activate
            # cd ..

        - name: Build
          run: |
            python hello-world-webapp.py

            # export FLASK_APP=hello-world-webapp
            # flask run
            echo "build is successfull"

    artifacts-upload:
        runs-on: ubuntu-latest
        needs: Build

        steps:
        - name: repository-checkout
          uses: actions/checkout@v3

        - name: 'creating path'
          run: |
            mkdir -p path/to/artifact
            echo hello > path/to/artifact/world.txt

        - name: 'Upload Artifact'
          uses: actions/upload-artifact@v3
          with:
            name: new-artifact
            path: path/to/artifact/world.txt
