name: helloworld-webapp
on: 
  push:
    branches: 
      - feature/tajuddin
jobs:
    python-setup:
      runs-on: ubuntu-latest
      steps:
        - name: python setup
          uses: actions/setup-python@v3
          with:
            python-version: '3.x'

        # - name: repository-checkout
        #   uses: actions/checkout@v3

        - name: installing the dependencies
          run: |
            sudo apt install -y python3-pip
            python3 -m pip install PyPI
            python3 -V
            echo "python setup is completed"

    Build:
        runs-on: ubuntu-latest
        needs: python-setup

        steps:
        - name: repository-checkout
        - uses: actions/checkout@v3

        - name:
          run: |
            echo "settingup dev-environment"

            # sudo apt install -y python3-venv
            # mkdir environments
            # cd environments
            # python3 -m venv development
            # source development/bin/activate
            # cd ..

            # pip install flask
            # python3 -c "import flask; print(flask.__version__)"

            python hello-world-webapp.py

            # export FLASK_APP=hello-world-webapp
            # flask run
            # echo "build is successfull"
