name: assessment

on:
  pull_request:
    types:
      - closed

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: 3.x  # Specify the desired Python version

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt  # Install your project's dependencies


      - name: Run workflow only on merged PRs to main
        if: ${{ github.event.pull_request.base.ref == 'main' && github.event.pull_request.merged == true }}
        run: |
          # This workflow will only execute if a pull request is closed and merged into the main branch
          # python app.py


      - name: Create release
        id: create_release
        uses: actions/create-release@v3
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: v1.0.0  # Specify the tag name for the release
          release_name: Release v1.0.0  # Specify the release name
          draft: false
          prerelease: false



