name: assessment

on:
  push:
    branches:
      - feature/taj

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Build artifacts
        run: |
          # Run your build command or script
          # python app.py
          # Copy app.py to a deployment directory
          mkdir deployment
          cp ./app.py deployment/app.py
      - name: Archive artifacts
        uses: actions/upload-artifact@v2
        with:
          name: my-artifacts
          path: deployment

  release:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Determine new version
        id: new_version
        run: |
          latest_tag=$(git ls-remote --tags origin | awk '{print $2}' | grep -E -o 'refs/tags/v[0-9]+\.[0-9]+\.[0-9]+' | sort -V | tail -n 1)
          if [ -z "$latest_tag" ]; then
            version="v1.0.0"
          else
            version_number=$(echo "$latest_tag" | grep -E -o '[0-9]+\.[0-9]+\.[0-9]+')
            version_parts=(${version_number//./ })
            major=${version_parts[0]}
            minor=${version_parts[1]}
            patch=${version_parts[2]}
            ((patch++))
            version="v${major}.${minor}.${patch}"
          fi
          echo "::set-output name=new_version::$version"
        shell: bash
      - name: Create release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.PAT_TOKEN }}
        with:
          tag_name: ${{ steps.new_version.outputs.new_version }}
          release_name: Release ${{ steps.new_version.outputs.new_version }}
          draft: false
          prerelease: false



      - name: Upload release asset
        id: upload_asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.PAT_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: deployment/app.py
          asset_name: app.py
          asset_content_type: text/x-python

  deploy:
    needs: release
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Download release asset
        uses: actions/github-script@v4
        with:
          script: |
            const fs = require('fs');
            const path = require('path');
            async function downloadReleaseAsset() {
              try {
                const { data: releases } = await github.repos.listReleases({
                  owner: context.repo.owner,
                  repo: context.repo.repo,
                  per_page: 1,
                });
                const release = releases[0];
                const { data: assets } = await github.repos.listReleaseAssets({
                  owner: context.repo.owner,
                  repo: context.repo.repo,
                  release_id: release.id,
                });
                const asset = assets.find(a => a.name === 'app.py');
                const response = await github.repos.getReleaseAsset({
                  owner: context.repo.owner,
                  repo: context.repo.repo,
                  asset_id: asset.id,
                });
                const deploymentPath = path.join(process.env.GITHUB_WORKSPACE, 'deployment');
                fs.mkdirSync(deploymentPath, { recursive: true });
                fs.writeFileSync(path.join(deploymentPath, 'app.py'), response.data);
              } catch (error) {
                console.error(error);
                process.exit(1);
              }
            }
            downloadReleaseAsset();
