name: assessment

on:
  push:
    branches:
      - feature/taj

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Build artifacts
        run: |
          mkdir deployment
          cp ./app.py deployment/app.py

      - name: Archive artifacts
        uses: actions/upload-artifact@v2
        with:
          name: my-artifacts
          path: deployment

  release:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Determine last release version
        id: last_release
        run: |
          last_version=$(git describe --tags --abbrev=0 2>/dev/null || echo "v1.0.0")
          echo "::set-output name=last_version::$last_version"
          echo "LAST_VERSION=${last_version}" >> $GITHUB_ENV

      - name: Determine new version
        id: new_version
        run: |
          last_version=${{ env.LAST_VERSION }}
          if [[ $last_version == "v1.0.0" ]]; then
            new_version="v1.0.0"
          else
            version_parts=($(echo "$last_version" | tr -d 'v' | tr '.' ' '))
            major=${version_parts[0]}
            minor=${version_parts[1]}
            patch=$((version_parts[2]+1))
            new_version="v${major}.${minor}.${patch}"
          fi
          echo "::set-output name=new_version::$new_version"
          echo "NEW_VERSION=${new_version}" >> $GITHUB_ENV

      - name: Download artifact
        uses: actions/download-artifact@v2
        with:
          name: my-artifacts
          path: deployment

      - name: Create release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.PAT_TOKEN }}
        with:
          tag_name: ${{ env.NEW_VERSION }}-$(date +'%Y%m%d%H%M%S')
          release_name: Release ${{ env.NEW_VERSION }}
          draft: false
          prerelease: false
      - name: Upload release asset
        id: upload_asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.PAT_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: deployment/app.py
          asset_name: app.py
          asset_content_type: text/x-python

  deploy:
    needs: release
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Download release asset
        uses: actions/github-script@v4
        with:
          script: |
            const fs = require('fs');
            const path = require('path');
            async function downloadReleaseAsset() {
              try {
                const { data: releases } = await github.repos.listReleases({
                  owner: context.repo.owner,
                  repo: context.repo.repo,
                  per_page: 1,
                });
                const release = releases[0];
                const { data: assets } = await github.repos.listReleaseAssets({
                  owner: context.repo.owner,
                  repo: context.repo.repo,
                  release_id: release.id,
                });
                const asset = assets.find(a => a.name === 'app.py');
                const response = await github.repos.getReleaseAsset({
                  owner: context.repo.owner,
                  repo: context.repo.repo,
                  asset_id: asset.id,
                });
                const deploymentPath = path.join(process.env.GITHUB_WORKSPACE, 'deployment');
                fs.mkdirSync(deploymentPath, { recursive: true });
                fs.writeFileSync(path.join(deploymentPath, 'app.py'), response.data);
              } catch (error) {
                console.error(error);
                process.exit(1);
              }
            }
            downloadReleaseAsset();
