name: assessment

on:
  pull_request:
    types:
      - closed

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: 3.x  # Specify the desired Python version

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt  # Install your project's dependencies


      - name: Run workflow only on merged PRs to main
        if: ${{ github.event.pull_request.base.ref == 'main' && github.event.pull_request.merged == true }}
        run: |
          # This workflow will only execute if a pull request is closed and merged into the main branch
          # python app.py


  artifacts:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v2
      - uses: actions/upload-artifact@v2
        with:
          name: my-artifact
          path: main.py

  deploy:
    runs-on: self-hosted
    needs: artifacts
    steps:
      - uses: actions/checkout@v2
      - uses: actions/download-artifact@v2
        with:
          name: my-artifact
          path: main.py
      - name: Deploy to server
        run: |
          python main.py

